services:
  osrubn:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/bootloader
    command: make clean && make -j$(nproc) output && qemu-system-x86_64 -drive format=raw,file=bootloader.img -m 512M -display gtk
    networks:
      - app-network

networks:
  app-network:
    driver: bridge